#ifndef BASEDEFINITIONS_H
#define BASEDEFINITIONS_H

#define TYPES_OF_MACHINES 7
#define TYPES_OF_BLOCKS 2
#define MINIMUM_ITEM_SPACING 5
#define TYPES_OF_ITEMS 5
#define ID_ITEM_STONE 0
#define ID_ITEM_COAL 1
#define ID_ITEM_CAIRN 2
#define ID_ITEM_SAND 3
#define ID_ITEM_GLASS 4

#define ID_MACHINE_CENTER 0
#define ID_MACHINE_CUTTER 1
#define ID_MACHINE_RUBBISHBIN 2
#define ID_MACHINE_DRILLER 3
#define ID_MACHINE_CONVEYOR 4
#define ID_MACHINE_BALLMILL 5
#define ID_MACHINE_KILN 6
#endif // BASEDEFINITIONS_H
